name: Trigger auto deployment for application-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/application-service-AutoDeployTrigger-68783aab-b4cc-4d37-adb8-8c631d563fce.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APPLICATIONSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPLICATIONSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPLICATIONSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/application-service
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.APPLICATIONSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPLICATIONSERVICE_REGISTRY_PASSWORD }}
          containerAppName: application-service
          resourceGroup: HireSphere-RG
          imageToBuild: gamithu/application-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


